// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SalesForce.TestFeature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("03 Create Organisation")]
    [NUnit.Framework.CategoryAttribute("Organisation")]
    public partial class _03CreateOrganisationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateOrganisation.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "03 Create Organisation", "\tIn order to manage customer and supplier data\r\n\tAs a CCS entity\r\n\tI want to have" +
                    " a mechanism to input organisation data", ProgrammingLanguage.CSharp, new string[] {
                        "Organisation"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
    testRunner.Given("I am on Select New Organisation Record Type page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 User Creates a new Supplier Organisation")]
        [NUnit.Framework.CategoryAttribute("RegressionTest")]
        [NUnit.Framework.TestCaseAttribute("Supplier", "Supplier001", "Central Government", "Health", "456789012", "0.5", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Supplier", "Supplier002", "Local Government", "County Council", "345678901", "1.2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Supplier", "Supplier003", "Police", "Police Authority", "234567890", "1.0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Supplier", "Supplier004", "Private", "Private Sector Enabler", "123456789", "1.5", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Supplier", "Supplier005", "Utility", "Energy", "012345678", "0.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Supplier", "Supplier006", "Health", "GP Practice", "567890123", "5", new string[0])]
        public virtual void _01UserCreatesANewSupplierOrganisation(string organisation, string organisationName, string sector, string organisationType, string dunsNumber, string indirectSME, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegressionTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 User Creates a new Supplier Organisation", @__tags);
#line 11
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 12
 testRunner.When(string.Format("I Select Organisation Record Type as {0}", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.And("Click on Continue button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("I should be presented with organisation Edit Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.When(string.Format("I enter mandatory information for supplier {0}, {1}, {2}, {3}, {4}", organisationName, sector, organisationType, dunsNumber, indirectSME), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.And("click on Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.Then(string.Format("a new organisation {0} would be created", organisationName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 User creates Customer organisation")]
        [NUnit.Framework.TestCaseAttribute("Organisation", "Customer001", "Central Government", "Health", "Active", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Organisation", "Customer002", "Education", "Colleges of Higher Education", "Active", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Organisation", "Customer003", "Local Government", "County Council", "Active", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Organisation", "Customer004", "Police", "Police Authority", "Active", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Organisation", "Customer005", "Private", "Private Sector Enabler", "Active", new string[0])]
        public virtual void _02UserCreatesCustomerOrganisation(string organisation, string organisationName, string sector, string organisationType, string status, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 User creates Customer organisation", exampleTags);
#line 27
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 28
 testRunner.When(string.Format("I Select Organisation Record Type as {0}", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.And("Click on Continue button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.Then("I should be presented with organisation Edit Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.When(string.Format("I enter mandatory information for customer {0}, {1}, {2}, {3}", organisationName, sector, organisationType, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.And("click on Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.Then(string.Format("a new organisation {0} would be created", organisationName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
